# Generated by Django 3.1.7 on 2021-05-23 21:43

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('designer', 'Designer'), ('engineer', 'Support Engineer'), ('developer', 'Front-end Developer'), ('witer', 'Content Writer')], max_length=50)),
                ('profissao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=10)),
                ('band', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('lni-coffee-cup', 'coffee-cup'), ('lni-invention', 'invention'), ('lni-reload', 'reload'), ('lni-briefcase', 'briefcase'), ('lni-layers', 'layers'), ('lni-support', 'support')], max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('featuresintroducao', models.TextField(max_length=1000)),
                ('features', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=150)),
                ('tempo_leitura', models.IntegerField()),
                ('data', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(upload_to='imagens/blog/')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=500)),
                ('icone', models.CharField(choices=[('lni-cog', 'cog'), ('lni-brush', 'brush'), ('lni-heart', 'heart')], max_length=20)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/showcase/')),
            ],
            options={
                'verbose_name': 'Show Case',
                'verbose_name_plural': 'Show Cases',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('imagem', stdimage.models.StdImageField(upload_to='imagens/testimonial/<function utilizando_imagem at 0x7f4cb73164c0>')),
                ('depoimento', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('facebook', models.CharField(default='#', max_length=50)),
                ('twitter', models.CharField(default='#', max_length=50)),
                ('gmail', models.CharField(default='#', max_length=50)),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.cargo')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instalation', models.CharField(max_length=10)),
                ('storage', models.IntegerField()),
                ('user', models.CharField(max_length=10)),
                ('bandwith', models.CharField(max_length=10)),
                ('features', models.CharField(max_length=10)),
                ('dashboar', models.CharField(max_length=10)),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.espaco')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
            },
        ),
    ]
